FROM node:12.13-alpine As fe_development

# set working directory
WORKDIR /usr/src/app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
RUN npm install react-scripts@3.4.1 -g --silent
RUN npm install -g yarn
RUN yarn install

# add app
COPY . ./

EXPOSE 3000