version: '3.7'

services:
  main:
    container_name: main
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: be_development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: yarn start:dev
    env_file:
      - ./backend/env
    networks:
      - webnet
    depends_on:
      - postgres
  # redis:
  #   container_name: redis
  #   image: redis:5
  #   networks:
  #     - webnet
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    stdin_open: true
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: yarn start
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - webnet
    depends_on:
      - main

networks:
  webnet:
volumes:
  pgdata:
